### ISSUE TITLE
复制文件名和路径会报错

### ISSUE THREAD

**Issue by DATOULIN** [lishaobos/svg-preview-plugin#1]
![image](https://user-images.githubusercontent.com/34710011/141417342-3b96240a-6a36-4a69-8d9d-9afe2a6ce041.png)

**Comment by lishaobos** [comment]
你好，复制我是基于浏览器的原生 api： navigator.clipboard.writeText，应该是浏览器的兼容

可以参考：https://caniuse.com/?search=navigator.clipboard.writeText

**Comment by DATOULIN** [comment]
感谢回复，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月12日(星期五) 下午2:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lishaobos/svg-preview-plugin] 复制文件名和路径会报错 (Issue #1)





 
你好，复制我是基于浏览器的原生 api： navigator.clipboard.writeText，应该是浏览器的兼容
 
可以参考：https://caniuse.com/?search=navigator.clipboard.writeText
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lishaobos** [comment]
你好，复制我是基于浏览器的原生 api： navigator.clipboard.writeText，应该是浏览器的兼容

可以参考：https://caniuse.com/?search=navigator.clipboard.writeText

**Comment by DATOULIN** [comment]
谢谢

**Comment by lishaobos** [comment]
不客气，有啥建议也可以告诉我
