### ISSUE TITLE
feat：考虑formatName的时候，多传递一个path变量吗？

### ISSUE THREAD

**Issue by wan-kong** [lishaobos/svg-preview-plugin#2]
svg很多个，所以是按目录划分的。name就会变成path-filename。
能在format 的时候把path也传进来吗？就算是完整的路径也行：)

**Comment by lishaobos** [comment]
好想法！

**Comment by lishaobos** [comment]
> svg很多个，所以是按目录划分的。name就会变成path-filename。 能在format 的时候把path也传进来吗？就算是完整的路径也行：)

0.50 版本

**Comment by wan-kong** [comment]
> > svg很多个，所以是按目录划分的。name就会变成path-filename。 能在format 的时候把path也传进来吗？就算是完整的路径也行：)
> 
> 0.50 版本

哥，你发包的时候，是不是忘了把dist丢进去了。。。

**Comment by lishaobos** [comment]
> > > svg很多个，所以是按目录划分的。name就会变成path-filename。 能在format 的时候把path也传进来吗？就算是完整的路径也行：)
> > 
> > 
> > 0.50 版本
> 
> 哥，你发包的时候，是不是忘了把dist丢进去了。。。

0.5.2，我使用的发包工具忽略了，我调整了下
